<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Modeling Practice and Qualifying Times | Visualizing Formula 1 Data in R</title>
  <meta name="description" content="This is a book documenting data visualizations of Formula 1 data." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Modeling Practice and Qualifying Times | Visualizing Formula 1 Data in R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/F1_book_cover.PNG" />
  <meta property="og:description" content="This is a book documenting data visualizations of Formula 1 data." />
  <meta name="github-repo" content="casanscott/vizf1book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Modeling Practice and Qualifying Times | Visualizing Formula 1 Data in R" />
  
  <meta name="twitter:description" content="This is a book documenting data visualizations of Formula 1 data." />
  <meta name="twitter:image" content="/F1_book_cover.PNG" />

<meta name="author" content="Casan Scott, Ph.D." />


<meta name="date" content="2024-02-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="qualifying.html"/>
<link rel="next" href="drivers.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Visualizing Formula 1 Data in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About the book</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#cover-art"><i class="fa fa-check"></i><b>1.1</b> Cover Art</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#about-me"><i class="fa fa-check"></i><b>1.2</b> About me</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#why-did-i-write-this-book"><i class="fa fa-check"></i><b>1.3</b> Why did I write this book?</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#organization-of-this-book"><i class="fa fa-check"></i><b>1.4</b> Organization of this book</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#r"><i class="fa fa-check"></i><b>1.5</b> R</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#ggplot2"><i class="fa fa-check"></i><b>1.6</b> ggplot2</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#the-tidyverse"><i class="fa fa-check"></i><b>1.7</b> The <em>tidyverse</em></a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#data"><i class="fa fa-check"></i><b>1.8</b> Data</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#data-visualization"><i class="fa fa-check"></i><b>1.9</b> Data Visualization</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-formula-1.html"><a href="introduction-to-formula-1.html"><i class="fa fa-check"></i><b>2</b> Introduction to Formula 1</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-formula-1.html"><a href="introduction-to-formula-1.html#data-1"><i class="fa fa-check"></i><b>2.1</b> Data</a></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-formula-1.html"><a href="introduction-to-formula-1.html#a-formula-1-weekend"><i class="fa fa-check"></i><b>2.2</b> A Formula 1 Weekend</a></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-formula-1.html"><a href="introduction-to-formula-1.html#practice-sessions"><i class="fa fa-check"></i><b>2.3</b> Practice Sessions</a></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-formula-1.html"><a href="introduction-to-formula-1.html#practice-times-by-driver"><i class="fa fa-check"></i><b>2.4</b> Practice Times by Driver</a></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-formula-1.html"><a href="introduction-to-formula-1.html#next-chapter"><i class="fa fa-check"></i><b>2.5</b> Next Chapter</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="qualifying.html"><a href="qualifying.html"><i class="fa fa-check"></i><b>3</b> Qualifying</a>
<ul>
<li class="chapter" data-level="3.1" data-path="qualifying.html"><a href="qualifying.html#distribution-of-qualifying-times-by-session"><i class="fa fa-check"></i><b>3.1</b> Distribution of Qualifying Times by Session</a></li>
<li class="chapter" data-level="3.2" data-path="qualifying.html"><a href="qualifying.html#distribution-of-qualifying-times-by-year"><i class="fa fa-check"></i><b>3.2</b> Distribution of Qualifying Times by Year</a></li>
<li class="chapter" data-level="3.3" data-path="qualifying.html"><a href="qualifying.html#qualifying-times-by-grand-prix"><i class="fa fa-check"></i><b>3.3</b> Qualifying Times by Grand Prix</a></li>
<li class="chapter" data-level="3.4" data-path="qualifying.html"><a href="qualifying.html#car-progression-over-time"><i class="fa fa-check"></i><b>3.4</b> Car Progression Over Time</a></li>
<li class="chapter" data-level="3.5" data-path="qualifying.html"><a href="qualifying.html#next-chapter-1"><i class="fa fa-check"></i><b>3.5</b> Next Chapter</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="modeling-practice-and-qualifying-times.html"><a href="modeling-practice-and-qualifying-times.html"><i class="fa fa-check"></i><b>4</b> Modeling Practice and Qualifying Times</a>
<ul>
<li class="chapter" data-level="4.1" data-path="modeling-practice-and-qualifying-times.html"><a href="modeling-practice-and-qualifying-times.html#models"><i class="fa fa-check"></i><b>4.1</b> Models</a></li>
<li class="chapter" data-level="4.2" data-path="modeling-practice-and-qualifying-times.html"><a href="modeling-practice-and-qualifying-times.html#simple-linear-regression-model-practice-vs-qualifying-times"><i class="fa fa-check"></i><b>4.2</b> Simple Linear Regression Model: Practice vs Qualifying Times</a></li>
<li class="chapter" data-level="4.3" data-path="modeling-practice-and-qualifying-times.html"><a href="modeling-practice-and-qualifying-times.html#simple-linear-regression-model-qualifying-time-vs-year"><i class="fa fa-check"></i><b>4.3</b> Simple Linear Regression Model: Qualifying time vs Year</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="modeling-practice-and-qualifying-times.html"><a href="modeling-practice-and-qualifying-times.html#uncertainty-in-model-estimates"><i class="fa fa-check"></i><b>4.3.1</b> Uncertainty in model estimates</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="modeling-practice-and-qualifying-times.html"><a href="modeling-practice-and-qualifying-times.html#interaction-model"><i class="fa fa-check"></i><b>4.4</b> Interaction Model</a></li>
<li class="chapter" data-level="4.5" data-path="modeling-practice-and-qualifying-times.html"><a href="modeling-practice-and-qualifying-times.html#next-chapter-2"><i class="fa fa-check"></i><b>4.5</b> Next Chapter</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="drivers.html"><a href="drivers.html"><i class="fa fa-check"></i><b>5</b> Drivers</a>
<ul>
<li class="chapter" data-level="5.1" data-path="drivers.html"><a href="drivers.html#race-performance"><i class="fa fa-check"></i><b>5.1</b> Race Performance</a></li>
<li class="chapter" data-level="5.2" data-path="drivers.html"><a href="drivers.html#qualifying-pace"><i class="fa fa-check"></i><b>5.2</b> Qualifying Pace</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="drivers.html"><a href="drivers.html#section"><i class="fa fa-check"></i><b>5.2.1</b> 2023</a></li>
<li class="chapter" data-level="5.2.2" data-path="drivers.html"><a href="drivers.html#section-1"><i class="fa fa-check"></i><b>5.2.2</b> 2022</a></li>
<li class="chapter" data-level="5.2.3" data-path="drivers.html"><a href="drivers.html#section-2"><i class="fa fa-check"></i><b>5.2.3</b> 2021</a></li>
<li class="chapter" data-level="5.2.4" data-path="drivers.html"><a href="drivers.html#section-3"><i class="fa fa-check"></i><b>5.2.4</b> 2020</a></li>
<li class="chapter" data-level="5.2.5" data-path="drivers.html"><a href="drivers.html#section-4"><i class="fa fa-check"></i><b>5.2.5</b> 2019</a></li>
<li class="chapter" data-level="5.2.6" data-path="drivers.html"><a href="drivers.html#section-5"><i class="fa fa-check"></i><b>5.2.6</b> 2018</a></li>
<li class="chapter" data-level="5.2.7" data-path="drivers.html"><a href="drivers.html#section-6"><i class="fa fa-check"></i><b>5.2.7</b> 2017</a></li>
<li class="chapter" data-level="5.2.8" data-path="drivers.html"><a href="drivers.html#section-7"><i class="fa fa-check"></i><b>5.2.8</b> 2016</a></li>
<li class="chapter" data-level="5.2.9" data-path="drivers.html"><a href="drivers.html#section-8"><i class="fa fa-check"></i><b>5.2.9</b> 2015</a></li>
<li class="chapter" data-level="5.2.10" data-path="drivers.html"><a href="drivers.html#section-9"><i class="fa fa-check"></i><b>5.2.10</b> 2014</a></li>
<li class="chapter" data-level="5.2.11" data-path="drivers.html"><a href="drivers.html#next-chapter-3"><i class="fa fa-check"></i><b>5.2.11</b> Next Chapter</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modeling-race-results.html"><a href="modeling-race-results.html"><i class="fa fa-check"></i><b>6</b> Modeling Race Results</a>
<ul>
<li class="chapter" data-level="6.1" data-path="modeling-race-results.html"><a href="modeling-race-results.html#starting-position-vs-finish-position"><i class="fa fa-check"></i><b>6.1</b> Starting Position vs Finish Position</a></li>
<li class="chapter" data-level="6.2" data-path="modeling-race-results.html"><a href="modeling-race-results.html#shortcomings-of-a-simple-linear-regression-model"><i class="fa fa-check"></i><b>6.2</b> Shortcomings of a simple linear regression model</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="modeling-race-results.html"><a href="modeling-race-results.html#linearity"><i class="fa fa-check"></i><b>6.2.1</b> Linearity</a></li>
<li class="chapter" data-level="6.2.2" data-path="modeling-race-results.html"><a href="modeling-race-results.html#homoscedasticity"><i class="fa fa-check"></i><b>6.2.2</b> Homoscedasticity</a></li>
<li class="chapter" data-level="6.2.3" data-path="modeling-race-results.html"><a href="modeling-race-results.html#independence"><i class="fa fa-check"></i><b>6.2.3</b> Independence</a></li>
<li class="chapter" data-level="6.2.4" data-path="modeling-race-results.html"><a href="modeling-race-results.html#normality"><i class="fa fa-check"></i><b>6.2.4</b> Normality</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="modeling-race-results.html"><a href="modeling-race-results.html#ordinal-regression-model"><i class="fa fa-check"></i><b>6.3</b> Ordinal regression model</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="modeling-race-results.html"><a href="modeling-race-results.html#prediction-grid"><i class="fa fa-check"></i><b>6.3.1</b> Prediction Grid</a></li>
<li class="chapter" data-level="6.3.2" data-path="modeling-race-results.html"><a href="modeling-race-results.html#yearly-differences-in-ordinal-regression-results"><i class="fa fa-check"></i><b>6.3.2</b> Yearly Differences in Ordinal Regression Results</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="modeling-race-results.html"><a href="modeling-race-results.html#explore-circuit-specific-models"><i class="fa fa-check"></i><b>6.4</b> Explore Circuit Specific Models</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="modeling-race-results.html"><a href="modeling-race-results.html#bahrain"><i class="fa fa-check"></i><b>6.4.1</b> Bahrain</a></li>
<li class="chapter" data-level="6.4.2" data-path="modeling-race-results.html"><a href="modeling-race-results.html#saudi-arabia"><i class="fa fa-check"></i><b>6.4.2</b> Saudi Arabia</a></li>
<li class="chapter" data-level="6.4.3" data-path="modeling-race-results.html"><a href="modeling-race-results.html#monaco"><i class="fa fa-check"></i><b>6.4.3</b> Monaco</a></li>
<li class="chapter" data-level="6.4.4" data-path="modeling-race-results.html"><a href="modeling-race-results.html#brazil"><i class="fa fa-check"></i><b>6.4.4</b> Brazil</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="modeling-race-results.html"><a href="modeling-race-results.html#appendix-probability-distributions-for-every-grand-prix"><i class="fa fa-check"></i><b>6.5</b> Appendix: Probability distributions for every Grand Prix</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="modeling-race-results.html"><a href="modeling-race-results.html#bahrain-1"><i class="fa fa-check"></i><b>6.5.1</b> Bahrain</a></li>
<li class="chapter" data-level="6.5.2" data-path="modeling-race-results.html"><a href="modeling-race-results.html#saudi-arabia-1"><i class="fa fa-check"></i><b>6.5.2</b> Saudi Arabia</a></li>
<li class="chapter" data-level="6.5.3" data-path="modeling-race-results.html"><a href="modeling-race-results.html#australia"><i class="fa fa-check"></i><b>6.5.3</b> Australia</a></li>
<li class="chapter" data-level="6.5.4" data-path="modeling-race-results.html"><a href="modeling-race-results.html#azerbaijan"><i class="fa fa-check"></i><b>6.5.4</b> Azerbaijan</a></li>
<li class="chapter" data-level="6.5.5" data-path="modeling-race-results.html"><a href="modeling-race-results.html#miami"><i class="fa fa-check"></i><b>6.5.5</b> Miami</a></li>
<li class="chapter" data-level="6.5.6" data-path="modeling-race-results.html"><a href="modeling-race-results.html#emilia-romagna"><i class="fa fa-check"></i><b>6.5.6</b> Emilia Romagna</a></li>
<li class="chapter" data-level="6.5.7" data-path="modeling-race-results.html"><a href="modeling-race-results.html#monaco-1"><i class="fa fa-check"></i><b>6.5.7</b> Monaco</a></li>
<li class="chapter" data-level="6.5.8" data-path="modeling-race-results.html"><a href="modeling-race-results.html#spain"><i class="fa fa-check"></i><b>6.5.8</b> Spain</a></li>
<li class="chapter" data-level="6.5.9" data-path="modeling-race-results.html"><a href="modeling-race-results.html#canada"><i class="fa fa-check"></i><b>6.5.9</b> Canada</a></li>
<li class="chapter" data-level="6.5.10" data-path="modeling-race-results.html"><a href="modeling-race-results.html#austria"><i class="fa fa-check"></i><b>6.5.10</b> Austria</a></li>
<li class="chapter" data-level="6.5.11" data-path="modeling-race-results.html"><a href="modeling-race-results.html#great-britain"><i class="fa fa-check"></i><b>6.5.11</b> Great Britain</a></li>
<li class="chapter" data-level="6.5.12" data-path="modeling-race-results.html"><a href="modeling-race-results.html#hungary"><i class="fa fa-check"></i><b>6.5.12</b> Hungary</a></li>
<li class="chapter" data-level="6.5.13" data-path="modeling-race-results.html"><a href="modeling-race-results.html#belgium"><i class="fa fa-check"></i><b>6.5.13</b> Belgium</a></li>
<li class="chapter" data-level="6.5.14" data-path="modeling-race-results.html"><a href="modeling-race-results.html#netherlands"><i class="fa fa-check"></i><b>6.5.14</b> Netherlands</a></li>
<li class="chapter" data-level="6.5.15" data-path="modeling-race-results.html"><a href="modeling-race-results.html#monza"><i class="fa fa-check"></i><b>6.5.15</b> Monza</a></li>
<li class="chapter" data-level="6.5.16" data-path="modeling-race-results.html"><a href="modeling-race-results.html#singapore"><i class="fa fa-check"></i><b>6.5.16</b> Singapore</a></li>
<li class="chapter" data-level="6.5.17" data-path="modeling-race-results.html"><a href="modeling-race-results.html#japan"><i class="fa fa-check"></i><b>6.5.17</b> Japan</a></li>
<li class="chapter" data-level="6.5.18" data-path="modeling-race-results.html"><a href="modeling-race-results.html#qatar"><i class="fa fa-check"></i><b>6.5.18</b> Qatar</a></li>
<li class="chapter" data-level="6.5.19" data-path="modeling-race-results.html"><a href="modeling-race-results.html#united-states-circuit-of-the-americas-in-austin-texas"><i class="fa fa-check"></i><b>6.5.19</b> United States (Circuit of the Americas in Austin, Texas)</a></li>
<li class="chapter" data-level="6.5.20" data-path="modeling-race-results.html"><a href="modeling-race-results.html#mexico"><i class="fa fa-check"></i><b>6.5.20</b> Mexico</a></li>
<li class="chapter" data-level="6.5.21" data-path="modeling-race-results.html"><a href="modeling-race-results.html#brazil-1"><i class="fa fa-check"></i><b>6.5.21</b> Brazil</a></li>
<li class="chapter" data-level="6.5.22" data-path="modeling-race-results.html"><a href="modeling-race-results.html#abu-dhabi"><i class="fa fa-check"></i><b>6.5.22</b> Abu Dhabi</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="modeling-race-results.html"><a href="modeling-race-results.html#next-chapter-4"><i class="fa fa-check"></i><b>6.6</b> Next Chapter</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="dnf-did-not-finish.html"><a href="dnf-did-not-finish.html"><i class="fa fa-check"></i><b>7</b> DNF (Did Not Finish)</a>
<ul>
<li class="chapter" data-level="7.1" data-path="dnf-did-not-finish.html"><a href="dnf-did-not-finish.html#logistic-regression"><i class="fa fa-check"></i><b>7.1</b> Logistic Regression</a></li>
<li class="chapter" data-level="7.2" data-path="dnf-did-not-finish.html"><a href="dnf-did-not-finish.html#yearly-differences"><i class="fa fa-check"></i><b>7.2</b> Yearly Differences</a></li>
<li class="chapter" data-level="7.3" data-path="dnf-did-not-finish.html"><a href="dnf-did-not-finish.html#differences-by-constructor"><i class="fa fa-check"></i><b>7.3</b> Differences by constructor</a></li>
<li class="chapter" data-level="7.4" data-path="dnf-did-not-finish.html"><a href="dnf-did-not-finish.html#dnfs-by-race-of-the-season"><i class="fa fa-check"></i><b>7.4</b> DNFs by race of the season</a></li>
<li class="chapter" data-level="7.5" data-path="dnf-did-not-finish.html"><a href="dnf-did-not-finish.html#next-chapter-5"><i class="fa fa-check"></i><b>7.5</b> Next Chapter</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="the-wdc-world-drivers-championship.html"><a href="the-wdc-world-drivers-championship.html"><i class="fa fa-check"></i><b>8</b> The WDC (World Drivers Championship)</a></li>
<li class="chapter" data-level="9" data-path="conclusions.html"><a href="conclusions.html"><i class="fa fa-check"></i><b>9</b> Conclusions</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Visualizing Formula 1 Data in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modeling-practice-and-qualifying-times" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Modeling Practice and Qualifying Times<a href="modeling-practice-and-qualifying-times.html#modeling-practice-and-qualifying-times" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>As mentioned in previous chapters, some runs during practice sessions are used to simulate qualifying or race pace. For instance, FP1 is typically used to test the car and ensure it is working as expected, while FP2 and FP3 are often used to test the car’s performance on <em>long runs</em> and the car’s speed over laps, respectively. Knowing this, I would expect practice times to correlate to qualifying times. This chapter will take a deep-dive into that relationship and try to better understand it.</p>
<p>Below, we can plot the best time set during FP1 versus the best time during Q1. For the most part, there is a near 1:1 ratio. However, there are several outlying clusters of times that don’t follow a 1:1 ratio.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="modeling-practice-and-qualifying-times.html#cb65-1" aria-hidden="true" tabindex="-1"></a>practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb65-2"><a href="modeling-practice-and-qualifying-times.html#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Time_secs_1, Q1_secs)) <span class="sc">+</span></span>
<span id="cb65-3"><a href="modeling-practice-and-qualifying-times.html#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb65-4"><a href="modeling-practice-and-qualifying-times.html#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb65-5"><a href="modeling-practice-and-qualifying-times.html#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Best Time during FP1 (secs)&#39;</span>,</span>
<span id="cb65-6"><a href="modeling-practice-and-qualifying-times.html#cb65-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Best Time during Q1 (secs)&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-59-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>One of these outlying clusters is data collected from the Malaysian Grand Prix in 2017. Free Practice 1 of the Malaysian Grand Prix in 2017 was delayed for half an hour due to heavy rain at the Sepang International Circuit. Max Verstappen eventually finished the wet FP1 session with a fastest time of 1:48.962. Qualifying was not impacted by rain, and Lewis Hamilton took pole with a time of 1:30.076. In the figure below, we can clearly see this relationship displayed by the <em>flatter</em> slope for the Malaysian Grand Prix in 2017.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="modeling-practice-and-qualifying-times.html#cb66-1" aria-hidden="true" tabindex="-1"></a>practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb66-2"><a href="modeling-practice-and-qualifying-times.html#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">malaysia_2017 =</span> <span class="fu">ifelse</span>(Race <span class="sc">==</span> <span class="st">&#39;malaysia&#39;</span> <span class="sc">&amp;</span> Year <span class="sc">==</span> <span class="dv">2017</span>, <span class="st">&#39;Malaysia 2017&#39;</span>, <span class="st">&#39;No&#39;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb66-3"><a href="modeling-practice-and-qualifying-times.html#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Time_secs_1, Q1_secs)) <span class="sc">+</span></span>
<span id="cb66-4"><a href="modeling-practice-and-qualifying-times.html#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">col =</span> malaysia_2017), <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">show.legend =</span> T) <span class="sc">+</span></span>
<span id="cb66-5"><a href="modeling-practice-and-qualifying-times.html#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb66-6"><a href="modeling-practice-and-qualifying-times.html#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Best Time during FP1 (secs)&#39;</span>,</span>
<span id="cb66-7"><a href="modeling-practice-and-qualifying-times.html#cb66-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Best Time during Q1 (secs)&#39;</span>) <span class="sc">+</span></span>
<span id="cb66-8"><a href="modeling-practice-and-qualifying-times.html#cb66-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gghighlight</span>(malaysia_2017 <span class="sc">==</span> <span class="st">&#39;Malaysia 2017&#39;</span>, <span class="at">use_direct_label =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb66-9"><a href="modeling-practice-and-qualifying-times.html#cb66-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="st">&#39;&#39;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&#39;Malaysia 2017&#39;</span> <span class="ot">=</span> <span class="st">&#39;black&#39;</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-60-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br>
<br></p>
<div class="blackbox">
<div class="center">
<p><strong>How to create a custom color scale in ggplot</strong></p>
</div>
<p>At times, creating custom color scales can be very convenient. The simplest way to create a custom color scale is by using <code>scale_color_manual()</code>. In the figure above, I used the following function to color data for <em>Malaysia 2017</em> black:</p>
<p><code>scale_color_manual('', values = c('Malaysia 2017' = 'black'))</code></p>
<p>For more information on using <code>scale_color_manual()</code> in <strong>ggplot2</strong>, visit this link: <a href="https://ggplot2.tidyverse.org/reference/scale_manual.html" class="uri">https://ggplot2.tidyverse.org/reference/scale_manual.html</a></p>
</div>
<p><br>
<br></p>
<p>I want to estimate the relationship between FP1 times and Q1 times, but these outlying clusters are compromising the relationship. In the Malaysia example above, rain was the root cause for a distinctly different slope (FP1 vs Q1). I want to remove these abnormal sessions, but it would be quite tedious to research all FP1 or Q1 sessions that were impacted by rain. As an alternative, I will utilize exploratory data analysis (EDA) and data wrangling to filter out abnormal times.</p>
<p>For the vast majority of Grands Prix, the slope of this relationship (FP1 times vs Q1 times) is slightly larger than 1. I’ll use a histogram below to plot the distribution of ratios of all FP1:Q1 times.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="modeling-practice-and-qualifying-times.html#cb67-1" aria-hidden="true" tabindex="-1"></a>practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb67-2"><a href="modeling-practice-and-qualifying-times.html#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ratio =</span> Time_secs_1 <span class="sc">/</span> Q1_secs) <span class="sc">%&gt;%</span> </span>
<span id="cb67-3"><a href="modeling-practice-and-qualifying-times.html#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(ratio)) <span class="sc">+</span> </span>
<span id="cb67-4"><a href="modeling-practice-and-qualifying-times.html#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">100</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb67-5"><a href="modeling-practice-and-qualifying-times.html#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb67-6"><a href="modeling-practice-and-qualifying-times.html#cb67-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Ratio of FP1:Q1 Times&#39;</span>,</span>
<span id="cb67-7"><a href="modeling-practice-and-qualifying-times.html#cb67-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&#39;Distribution of all Ratios of FP1:Q1 Times&#39;</span>,</span>
<span id="cb67-8"><a href="modeling-practice-and-qualifying-times.html#cb67-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&#39;2014 - 2022&#39;</span>) <span class="sc">+</span></span>
<span id="cb67-9"><a href="modeling-practice-and-qualifying-times.html#cb67-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="fl">0.7</span>, <span class="fl">1.3</span>), </span>
<span id="cb67-10"><a href="modeling-practice-and-qualifying-times.html#cb67-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">breaks =</span> <span class="fu">c</span>(<span class="fl">0.7</span>, <span class="fl">0.8</span>, <span class="fl">0.9</span>, <span class="dv">1</span>, <span class="fl">1.1</span>, <span class="fl">1.2</span>, <span class="fl">1.3</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-61-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>There are three separate peaks in this distribution:</p>
<ul>
<li>slightly larger than 1.0</li>
<li>just below 0.90</li>
<li>at approximately 1.15</li>
</ul>
<p>Knowing this information, I will try to filter out any ratios lower than 0.95 or larger than 1.10.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="modeling-practice-and-qualifying-times.html#cb68-1" aria-hidden="true" tabindex="-1"></a>practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb68-2"><a href="modeling-practice-and-qualifying-times.html#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ratio =</span> Time_secs_1 <span class="sc">/</span> Q1_secs) <span class="sc">%&gt;%</span> </span>
<span id="cb68-3"><a href="modeling-practice-and-qualifying-times.html#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ratio <span class="sc">&gt;=</span> <span class="fl">0.95</span> <span class="sc">&amp;</span> ratio <span class="sc">&lt;=</span> <span class="fl">1.10</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb68-4"><a href="modeling-practice-and-qualifying-times.html#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Time_secs_1, Q1_secs)) <span class="sc">+</span></span>
<span id="cb68-5"><a href="modeling-practice-and-qualifying-times.html#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb68-6"><a href="modeling-practice-and-qualifying-times.html#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb68-7"><a href="modeling-practice-and-qualifying-times.html#cb68-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Best Time during FP1 (secs)&#39;</span>,</span>
<span id="cb68-8"><a href="modeling-practice-and-qualifying-times.html#cb68-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Best Time during Q1 (secs)&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-62-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>That looks much better! There’s still a few funky outliers, but I feel comfortable that this distribution represents the typical Formula 1 weekend. While this graph is some evidence to suggest that FP1 times are <em>correlated</em> to Q1 times, I actually want to <em>quantify</em> this relationship. So, next, I will use a <strong>simple linear regression model</strong> to estimate the relationship between FP1 and Q1 times.</p>
<div id="models" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Models<a href="modeling-practice-and-qualifying-times.html#models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Why build a model? At the most basic level, we are looking for <em>relationships</em> between variables in our dataset. Models are mathematical mappings between variables… in a rather structured way. People generally build models for:</p>
<ul>
<li>making inferences (i.e. using a model to answer research questions)</li>
<li>making predictions</li>
<li>or both inference and prediction</li>
</ul>
<p>An example of an inferential model could be a logistic regression model used to estimate the effect that smoking has on someone’s likelihood of developing cancer. An example of predictive model is an election forecaster. But, inferential models can still be used to make predictions, and sometimes the predictive models can make inferences. In this chapter, I want to use an inferential models to make general claims about the relationship between practice times and qualifying times. In the next section, I’ll introduce <strong>regression</strong> models and demonstrate how to use them to learn about Formula 1.</p>
</div>
<div id="simple-linear-regression-model-practice-vs-qualifying-times" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Simple Linear Regression Model: Practice vs Qualifying Times<a href="modeling-practice-and-qualifying-times.html#simple-linear-regression-model-practice-vs-qualifying-times" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Dr. Andrew Gelman summarizes regression much more succinctly than I ever could:</p>
<p><em>Regression is a method that allows researchers to summarize how predictions or average values of an outcome vary across individuals defined by a set of predictors.</em></p>
<p>If you’ve ever created a scatterplot in Excel, the <em>best-fit</em> line is based on a linear regression between the variable on the x-axis and the variable on the y-axis. However, linear regression can be far more useful than a simple method to find the best-fit line. Throughout the rest of this chapter, I will introduce ways to summarize and communicate results from linear regression models. In this book, I will only briefly cover particularly important aspects of models. So, if you are in need of an introduction or refresher on regression, I <em>highly</em> recommend checking out the following introductory book on regression:</p>
<p><br>
<br></p>
<div class="blackbox">
<div class="center">
<p><strong>More information about linear regression in R</strong></p>
</div>
<p>My favorite introductory book on regression in R is <em>Regression and Other Stories</em> by Andrew Gelman, Jennifer Hill, and Aki Vehtari. This book focuses on the practical application of regression models in R, and includes tons of very helpful code. While the authors build bayesian models, I think it is helpful for anyone looking to learn about regression. Here’s a link to the free book and lots of example code:</p>
<p><a href="https://avehtari.github.io/ROS-Examples/index.html" class="uri">https://avehtari.github.io/ROS-Examples/index.html</a></p>
</div>
<p><br>
<br></p>
<p>The most simple <strong>linear regression</strong> model uses a single predictor variable. In our model, the single predictor is FP1 times. We will use linear regression model to fit a linear relationship (straight line) between the predictor variable (FP1 times) and the response variable (Q1 times). This model provides estimates of the <em>intercept</em>, <em>slope</em>, and <em>error</em>.</p>
<p>The formula for this simple linear regression model is:</p>
<p><span class="math display">\[ Q1 \ time = Intercept + Slope * FP1 \ time + error \]</span></p>
<p>I will fit the model to the filtered dataset I created earlier (i.e. with ratios between 0.95 and 1.10). Below, I’ll re-write this data to a new dataframe.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="modeling-practice-and-qualifying-times.html#cb69-1" aria-hidden="true" tabindex="-1"></a>fp1_v_q1_clean <span class="ot">&lt;-</span> practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb69-2"><a href="modeling-practice-and-qualifying-times.html#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ratio =</span> Time_secs_1 <span class="sc">/</span> Q1_secs) <span class="sc">%&gt;%</span> </span>
<span id="cb69-3"><a href="modeling-practice-and-qualifying-times.html#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ratio <span class="sc">&gt;=</span> <span class="fl">0.95</span> <span class="sc">&amp;</span> ratio <span class="sc">&lt;=</span> <span class="fl">1.10</span>)</span></code></pre></div>
<p>To fit a linear regression model to this data, I will use the <code>lm()</code> function.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="modeling-practice-and-qualifying-times.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fir the linear regression model</span></span>
<span id="cb70-2"><a href="modeling-practice-and-qualifying-times.html#cb70-2" aria-hidden="true" tabindex="-1"></a>fp1_v_q1.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Q1_secs <span class="sc">~</span> Time_secs_1, <span class="at">data =</span> fp1_v_q1_clean)</span></code></pre></div>
<p><br>
<br></p>
<div class="blackbox">
<div class="center">
<p><strong>How to fit a simple linear regression model in R</strong></p>
</div>
<p>To fit a simple linear regression model in R, we can use the <code>lm()</code> function.</p>
<p>The <code>lm()</code> function takes uses the following notation:</p>
<p><code>lm(response variable ~ predictor variable(s), data source)</code></p>
<p>For more information on using <code>lm()</code>, visit this link: <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/lm" class="uri">https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/lm</a></p>
</div>
<p><br>
<br></p>
<p>I will now use the <code>summary()</code> function to summarize the output from the linear model.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="modeling-practice-and-qualifying-times.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fp1_v_q1.model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Q1_secs ~ Time_secs_1, data = fp1_v_q1_clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.9836 -0.5859  0.0210  0.6408  8.3919 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1.610673   0.163619   9.844   &lt;2e-16 ***
## Time_secs_1 0.958841   0.001828 524.432   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.295 on 3200 degrees of freedom
## Multiple R-squared:  0.9885, Adjusted R-squared:  0.9885 
## F-statistic: 2.75e+05 on 1 and 3200 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The summary output from this model contains a lot of important information about this model fit. The following list gives a bit more information about the most noteworthy items in this summary output:</p>
<ul>
<li>The model formula is found under <em>Call</em>.</li>
<li>The quantiles of the residuals are listed below the model formula.</li>
<li>the coefficient values are the model estimates for intercept and slope. Each coefficient also has a standard error, t-values, and statistical significance.</li>
<li>The residual standard error</li>
<li>degrees of freedom</li>
<li>R-squared</li>
<li>F-statistic</li>
<li>p-value</li>
</ul>
<p>In this particular model, the <strong>Intercept</strong> is somewhat meaningless. The intercept describes the value of the response (Q1 times) when the predictor variable (FP1 time) is = 0. However, in this example, there is no situation where FP1 is = 0.</p>
<p>We can interpret the <strong>slope</strong> as:</p>
<p><em>A driver’s Q1 time is expected to be about 0.036 seconds faster than their best time during Free Practice 1, on average.</em></p>
<p>I arrived at 0.036 seconds by subtracting the slope from 1.</p>
<p>The <strong>R2</strong> is another important metric from this output. The <strong>R2</strong> value, also known as the coefficient of determination, is the proportion of the variance in Q1 times that are explained by FP1 time. In this case, the R2 = 0.989, which can be interpreted as ~ 98.9% of the variance in a driver’s Q1 time can be explained by their FP1 time.</p>
<p>The F-statistic is of little use to us in this case. The <em>F-statistic</em> is the test statistic for the <em>F-test</em>, which evaluates whether this particular model provides a better fit to our data than a model that uses no predictor variables. If the <em>p-value</em> is less than 0.05 (which it is), we conclude that this model is better than a model using no predictor variables. But, we already knew this linear relationship was legit. And, with really large datasets like this one, statistical significance can be a dubious concept.</p>
<p>For our purposes, we should be most concerned with the R2 and the slope of this model. The R2 explains the amount of variance that our model explains, while the slope describes how FP1 times and Q1 times related. We can apply this same approach to a different comparison: FP3 vs fastest qualifying time. Because FP3 is used for qualifying simulations, it may be more representative of a car’s true qualifying pace. Using the fastest time in qualifying is likely a better measure because front-running teams likely take less risks during Q1.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="modeling-practice-and-qualifying-times.html#cb73-1" aria-hidden="true" tabindex="-1"></a>fp3_v_q_clean <span class="ot">&lt;-</span> practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb73-2"><a href="modeling-practice-and-qualifying-times.html#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ratio =</span> Time_secs_3 <span class="sc">/</span> Q_secs) <span class="sc">%&gt;%</span> </span>
<span id="cb73-3"><a href="modeling-practice-and-qualifying-times.html#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ratio <span class="sc">&gt;=</span> <span class="fl">0.95</span> <span class="sc">&amp;</span> ratio <span class="sc">&lt;=</span> <span class="fl">1.10</span>)</span>
<span id="cb73-4"><a href="modeling-practice-and-qualifying-times.html#cb73-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-5"><a href="modeling-practice-and-qualifying-times.html#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fir the linear regression model</span></span>
<span id="cb73-6"><a href="modeling-practice-and-qualifying-times.html#cb73-6" aria-hidden="true" tabindex="-1"></a>fp3_v_q.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Q_secs <span class="sc">~</span> Time_secs_3, <span class="at">data =</span> fp3_v_q_clean)</span>
<span id="cb73-7"><a href="modeling-practice-and-qualifying-times.html#cb73-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-8"><a href="modeling-practice-and-qualifying-times.html#cb73-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fp3_v_q.model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Q_secs ~ Time_secs_3, data = fp3_v_q_clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.1310 -0.3914  0.0386  0.5222  6.5447 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1.210783   0.139942   8.652   &lt;2e-16 ***
## Time_secs_3 0.973464   0.001576 617.569   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.194 on 3584 degrees of freedom
## Multiple R-squared:  0.9907, Adjusted R-squared:  0.9907 
## F-statistic: 3.814e+05 on 1 and 3584 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="modeling-practice-and-qualifying-times.html#cb75-1" aria-hidden="true" tabindex="-1"></a>practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb75-2"><a href="modeling-practice-and-qualifying-times.html#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ratio =</span> Q_secs <span class="sc">/</span> Time_secs_3) <span class="sc">%&gt;%</span> </span>
<span id="cb75-3"><a href="modeling-practice-and-qualifying-times.html#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ratio <span class="sc">&gt;=</span> <span class="fl">0.95</span> <span class="sc">&amp;</span> ratio <span class="sc">&lt;=</span> <span class="fl">1.10</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb75-4"><a href="modeling-practice-and-qualifying-times.html#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Time_secs_3, Q_secs)) <span class="sc">+</span></span>
<span id="cb75-5"><a href="modeling-practice-and-qualifying-times.html#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb75-6"><a href="modeling-practice-and-qualifying-times.html#cb75-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb75-7"><a href="modeling-practice-and-qualifying-times.html#cb75-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Best Time during FP3 (secs)&#39;</span>,</span>
<span id="cb75-8"><a href="modeling-practice-and-qualifying-times.html#cb75-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Best Time during Qualifying (secs)&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-66-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>In this FP3 model, we can interpret the slope as:</p>
<p><em>A driver’s best time in qualifying is expected to be about 0.012 seconds faster than their best time during Free Practice 3, on average.</em></p>
<p>Again, I arrived at 0.012 seconds by subtracting the slope from 1.</p>
<p>This FP3 model explains fractionally more variance than the previous FP1 model (the R2 = 0.992 vs 0.989). So, FP3 times explain about 99.2% of the variance in a driver’s best qualifying time.</p>
<p>Pretty interesting!</p>
<p>Next, we’ll use a linear regression model to estimate the progression of qualifying times over time (i.e. by year).</p>
</div>
<div id="simple-linear-regression-model-qualifying-time-vs-year" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Simple Linear Regression Model: Qualifying time vs Year<a href="modeling-practice-and-qualifying-times.html#simple-linear-regression-model-qualifying-time-vs-year" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the last chapter, I created this figure to show the progression of qualifying times at the Australian Grand Prix.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="modeling-practice-and-qualifying-times.html#cb76-1" aria-hidden="true" tabindex="-1"></a>practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb76-2"><a href="modeling-practice-and-qualifying-times.html#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Race <span class="sc">==</span> <span class="st">&#39;australia&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb76-3"><a href="modeling-practice-and-qualifying-times.html#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rain =</span> <span class="fu">ifelse</span>(Year <span class="sc">==</span> <span class="dv">2014</span> <span class="sc">&amp;</span> Q_secs <span class="sc">&gt;</span> <span class="dv">100</span>, <span class="st">&#39;rain during Q2&#39;</span>, <span class="st">&#39; &#39;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb76-4"><a href="modeling-practice-and-qualifying-times.html#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(rain <span class="sc">==</span> <span class="st">&#39; &#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb76-5"><a href="modeling-practice-and-qualifying-times.html#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Year, Q_secs)) <span class="sc">+</span></span>
<span id="cb76-6"><a href="modeling-practice-and-qualifying-times.html#cb76-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">seed=</span> <span class="dv">123</span>, <span class="at">h =</span> <span class="dv">0</span>, <span class="at">w =</span> <span class="fl">0.3</span>), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb76-7"><a href="modeling-practice-and-qualifying-times.html#cb76-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="at">se =</span> F, <span class="at">size =</span> <span class="fl">0.3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb76-8"><a href="modeling-practice-and-qualifying-times.html#cb76-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb76-9"><a href="modeling-practice-and-qualifying-times.html#cb76-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Year&#39;</span>,</span>
<span id="cb76-10"><a href="modeling-practice-and-qualifying-times.html#cb76-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Best Qualifying Time (secs)&#39;</span>,</span>
<span id="cb76-11"><a href="modeling-practice-and-qualifying-times.html#cb76-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&#39;Australian Grand Prix Qualifying&#39;</span>,</span>
<span id="cb76-12"><a href="modeling-practice-and-qualifying-times.html#cb76-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&#39;2014 - 2023&#39;</span>) <span class="sc">+</span></span>
<span id="cb76-13"><a href="modeling-practice-and-qualifying-times.html#cb76-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">2014</span>, <span class="dv">2015</span>, <span class="dv">2016</span>, <span class="dv">2017</span>, <span class="dv">2018</span>, <span class="dv">2019</span>, <span class="dv">2020</span>, <span class="dv">2021</span>, <span class="dv">2022</span>, <span class="dv">2023</span>)) <span class="sc">+</span></span>
<span id="cb76-14"><a href="modeling-practice-and-qualifying-times.html#cb76-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb76-15"><a href="modeling-practice-and-qualifying-times.html#cb76-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-67-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>I used the <code>stat_smooth()</code> function to fit a best-fit line through the data. But, this was just a visual aid and I didn’t actually quantify the relationship between year and qualifying time. To quantify this relationship, a simple linear regression model can be used. The formula for this model is simply:</p>
<p><span class="math display">\[Qualifying \ time \sim intercept \ + \ Year \ + \ \epsilon\]</span></p>
<p>In the code below, I will:</p>
<ol style="list-style-type: decimal">
<li>filter the data to include only the Australian Grand Prix</li>
<li>remove sessions that were impacted by rain.</li>
</ol>
<p>I then fit a simple linear regression model using the <code>lm()</code> function.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="modeling-practice-and-qualifying-times.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filter times to include only clean Australian data</span></span>
<span id="cb77-2"><a href="modeling-practice-and-qualifying-times.html#cb77-2" aria-hidden="true" tabindex="-1"></a>aus_quali_times <span class="ot">&lt;-</span> practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb77-3"><a href="modeling-practice-and-qualifying-times.html#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Race <span class="sc">==</span> <span class="st">&#39;australia&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb77-4"><a href="modeling-practice-and-qualifying-times.html#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rain =</span> <span class="fu">ifelse</span>(Year <span class="sc">==</span> <span class="dv">2014</span> <span class="sc">&amp;</span> Q_secs <span class="sc">&gt;</span> <span class="dv">100</span>, <span class="st">&#39;rain during Q2&#39;</span>, <span class="st">&#39; &#39;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb77-5"><a href="modeling-practice-and-qualifying-times.html#cb77-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(rain <span class="sc">==</span> <span class="st">&#39; &#39;</span>,</span>
<span id="cb77-6"><a href="modeling-practice-and-qualifying-times.html#cb77-6" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(Q_secs))</span>
<span id="cb77-7"><a href="modeling-practice-and-qualifying-times.html#cb77-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-8"><a href="modeling-practice-and-qualifying-times.html#cb77-8" aria-hidden="true" tabindex="-1"></a><span class="co"># fit linear model</span></span>
<span id="cb77-9"><a href="modeling-practice-and-qualifying-times.html#cb77-9" aria-hidden="true" tabindex="-1"></a>aus.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Q_secs <span class="sc">~</span> Year, aus_quali_times)</span></code></pre></div>
<p>Below is a summary of the model output.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="modeling-practice-and-qualifying-times.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aus.lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Q_secs ~ Year, data = aus_quali_times)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.5408 -1.0523 -0.0226  0.7590  7.0584 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2913.43233  106.09863   27.46   &lt;2e-16 ***
## Year          -1.40194    0.05257  -26.67   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.767 on 141 degrees of freedom
## Multiple R-squared:  0.8346, Adjusted R-squared:  0.8334 
## F-statistic: 711.3 on 1 and 141 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Let’s try to interpret some of this output.</p>
<p>This model’s fitted line equation is simply:</p>
<p><span class="math display">\[ time_Q \sim 2913 - 1.40 * year + \epsilon\]</span></p>
<p>Like before, I am most interested in the <strong>coefficient estimates, residual standard error, and R2</strong>.</p>
<p><strong>intercept</strong>: For this particular model, the intercept reported in this ouput isn’t immediately useful. It tells us the estimated mean qualifying time for the year zero. A year zero does not exist in the <em>Anno Domini</em> calendar year system (the year 1 BC is followed directly by year AD 1), so not helpful! However, we can rescale it to the year 2014 and interpret the value like this:</p>
<p><em>The average qualifying time at the Australian Grand Prix during the initial year of the hybrid era (2014) was 93.4 seconds (2913 + (-1.40 x 2014).</em></p>
<p><strong>Slope</strong>:</p>
<p><em>Since the beginning of the hybrid era (2014), qualifying times in Australia decrease by 1.40 seconds per year, on average.</em></p>
<p>The <strong>R2</strong> value (coefficient of determination) is the proportion of the variance in Australian qualifying times that can be explained by yearly progression. In this case, the R2 = 0.83, which can be interpreted as:</p>
<p><em>83% of the variance in qualifying times can be explained by the year.</em></p>
<p>An approximate interpretation of the <strong>residual standard error/deviation (RSE)</strong> is:</p>
<p><em>A year’s qualifying times will deviate from the linear regression model fit line by 1.77 seconds, on average.</em></p>
<p>In the following section, I will discuss <em>uncertainty</em> in our model.</p>
<div id="uncertainty-in-model-estimates" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Uncertainty in model estimates<a href="modeling-practice-and-qualifying-times.html#uncertainty-in-model-estimates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the last section, I described the slope point estimate as: <em>Since the beginning of the hybrid era (2014), qualifying times in Australia decrease by 1.40 seconds per year, on average.</em> But, how sure am I of this number? A confidence interval allows us to also describe the uncertainty in that estimate. Below, I’ll calculate the 95% confidence interval around the slope estimate, and interpret it.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="modeling-practice-and-qualifying-times.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(aus.lm)</span></code></pre></div>
<pre><code>##                   2.5 %      97.5 %
## (Intercept) 2703.682609 3123.182046
## Year          -1.505856   -1.298015</code></pre>
<p><strong>95% Confidence Interval around the Slope</strong>:</p>
<p><em>Since the beginning of the hybrid era (2014), qualifying times in Australia decrease by 1.40 seconds per year, on average. We have 95% confidence that the true average decrease in Australian qualifying times per year is between 1.30 and 1.51 seconds, on average.</em></p>
<p>Let’s revisit the earlier plot of Australian Grand Prix qualifying times, with a best-fit line included. This line describes the linear regression model’s estimate of average qualifying time for each year of the race. Like we did with our slope estimate, we should describe our uncertainty around this line using a confidence and prediction interval.</p>
<p><strong>The confidence interval is uncertainty surrounding a <em>mean response</em>, and the prediction interval is uncertainty surrounding a prediction of a <em>single future observation</em>.</strong></p>
<p>The interpretation of the <strong>95% confidence interval</strong> of a predicted value is: <em>“95% of intervals of this form will contain the expected value of average qualifying time given a particular year.”</em></p>
<p>The interpretation of the <strong>95% prediction interval</strong> of a predicted value is: <em>“95% of intervals of this form will contain the true qualifying time for this particular year.”</em></p>
<p>Below, I will plot the 95% confidence interval around the fit.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="modeling-practice-and-qualifying-times.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb82-2"><a href="modeling-practice-and-qualifying-times.html#cb82-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-3"><a href="modeling-practice-and-qualifying-times.html#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the 95% confidence interval for the fit line</span></span>
<span id="cb82-4"><a href="modeling-practice-and-qualifying-times.html#cb82-4" aria-hidden="true" tabindex="-1"></a>aus_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(aus.lm, <span class="at">data =</span> aus_quali_times, <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>, <span class="at">se_fit =</span> T)</span>
<span id="cb82-5"><a href="modeling-practice-and-qualifying-times.html#cb82-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-6"><a href="modeling-practice-and-qualifying-times.html#cb82-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-7"><a href="modeling-practice-and-qualifying-times.html#cb82-7" aria-hidden="true" tabindex="-1"></a>aus_aug <span class="sc">%&gt;%</span> </span>
<span id="cb82-8"><a href="modeling-practice-and-qualifying-times.html#cb82-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Year, Q_secs)) <span class="sc">+</span></span>
<span id="cb82-9"><a href="modeling-practice-and-qualifying-times.html#cb82-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">seed=</span> <span class="dv">123</span>, <span class="at">h =</span> <span class="dv">0</span>, <span class="at">w =</span> <span class="fl">0.3</span>), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb82-10"><a href="modeling-practice-and-qualifying-times.html#cb82-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="at">se =</span> F, <span class="at">size =</span> <span class="fl">0.3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb82-11"><a href="modeling-practice-and-qualifying-times.html#cb82-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb82-12"><a href="modeling-practice-and-qualifying-times.html#cb82-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Year&#39;</span>,</span>
<span id="cb82-13"><a href="modeling-practice-and-qualifying-times.html#cb82-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Best Qualifying Time (secs)&#39;</span>,</span>
<span id="cb82-14"><a href="modeling-practice-and-qualifying-times.html#cb82-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&#39;Australian Grand Prix Qualifying&#39;</span>,</span>
<span id="cb82-15"><a href="modeling-practice-and-qualifying-times.html#cb82-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&#39;Linear Model, 95% CI (2014 - 2023)&#39;</span>) <span class="sc">+</span></span>
<span id="cb82-16"><a href="modeling-practice-and-qualifying-times.html#cb82-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">2014</span>, <span class="dv">2015</span>, <span class="dv">2016</span>, <span class="dv">2017</span>, <span class="dv">2018</span>, <span class="dv">2019</span>, <span class="dv">2022</span>, <span class="dv">2023</span>)) <span class="sc">+</span></span>
<span id="cb82-17"><a href="modeling-practice-and-qualifying-times.html#cb82-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> .lower, <span class="at">ymax =</span> .upper), <span class="at">fill =</span> <span class="st">&#39;grey&#39;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb82-18"><a href="modeling-practice-and-qualifying-times.html#cb82-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb82-19"><a href="modeling-practice-and-qualifying-times.html#cb82-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-71-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br>
<br></p>
<div class="blackbox">
<div class="center">
<p><strong>The <code>augment()</code> function from the broom package</strong></p>
</div>
<p>Augment accepts a model object and a dataset and adds information about each observation in the dataset. One of many conveniences provided by augment, is the ability to attach 95% confidence or prediction intervals to a dataframe.</p>
<p>In the example above, I use the following code to attach a predicted value and the 95% confidence interval to the Australia qualifying dataset:</p>
<p><code>augment(aus.lm, data = aus_quali_times, interval = "confidence", se_fit = T)</code></p>
<p>For more information on using <code>augment()</code>, visit this link: <a href="https://broom.tidymodels.org/reference/augment.lm.html" class="uri">https://broom.tidymodels.org/reference/augment.lm.html</a></p>
</div>
<p><br>
<br></p>
<p>And here, I will also include the 95% prediction interval.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="modeling-practice-and-qualifying-times.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the 95% prediction interval for the fit line</span></span>
<span id="cb83-2"><a href="modeling-practice-and-qualifying-times.html#cb83-2" aria-hidden="true" tabindex="-1"></a>aus_aug_pr <span class="ot">&lt;-</span> <span class="fu">augment</span>(aus.lm, <span class="at">data =</span> aus_quali_times, <span class="at">interval =</span> <span class="st">&quot;prediction&quot;</span>, <span class="at">se_fit =</span> T) <span class="sc">%&gt;%</span></span>
<span id="cb83-3"><a href="modeling-practice-and-qualifying-times.html#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rename</span>(<span class="st">&quot;lower_PI&quot;</span> <span class="ot">=</span> <span class="st">&quot;.lower&quot;</span>, <span class="st">&quot;upper_PI&quot;</span> <span class="ot">=</span> <span class="st">&quot;.upper&quot;</span>)</span>
<span id="cb83-4"><a href="modeling-practice-and-qualifying-times.html#cb83-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-5"><a href="modeling-practice-and-qualifying-times.html#cb83-5" aria-hidden="true" tabindex="-1"></a><span class="co"># combine the intervals</span></span>
<span id="cb83-6"><a href="modeling-practice-and-qualifying-times.html#cb83-6" aria-hidden="true" tabindex="-1"></a>aus_aug <span class="ot">&lt;-</span> aus_aug <span class="sc">%&gt;%</span></span>
<span id="cb83-7"><a href="modeling-practice-and-qualifying-times.html#cb83-7" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_cols</span>(aus_aug_pr <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(lower_PI, upper_PI))</span>
<span id="cb83-8"><a href="modeling-practice-and-qualifying-times.html#cb83-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-9"><a href="modeling-practice-and-qualifying-times.html#cb83-9" aria-hidden="true" tabindex="-1"></a>aus_aug <span class="sc">%&gt;%</span> </span>
<span id="cb83-10"><a href="modeling-practice-and-qualifying-times.html#cb83-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Year, Q_secs)) <span class="sc">+</span></span>
<span id="cb83-11"><a href="modeling-practice-and-qualifying-times.html#cb83-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">seed=</span> <span class="dv">123</span>, <span class="at">h =</span> <span class="dv">0</span>, <span class="at">w =</span> <span class="fl">0.3</span>), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb83-12"><a href="modeling-practice-and-qualifying-times.html#cb83-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="at">se =</span> F, <span class="at">size =</span> <span class="fl">0.3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb83-13"><a href="modeling-practice-and-qualifying-times.html#cb83-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb83-14"><a href="modeling-practice-and-qualifying-times.html#cb83-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Year&#39;</span>,</span>
<span id="cb83-15"><a href="modeling-practice-and-qualifying-times.html#cb83-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Best Qualifying Time (secs)&#39;</span>,</span>
<span id="cb83-16"><a href="modeling-practice-and-qualifying-times.html#cb83-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&#39;Australian Grand Prix Qualifying&#39;</span>,</span>
<span id="cb83-17"><a href="modeling-practice-and-qualifying-times.html#cb83-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&#39;Linear Model, 95% CI, and 95% PI (2014 - 2023)&#39;</span>) <span class="sc">+</span></span>
<span id="cb83-18"><a href="modeling-practice-and-qualifying-times.html#cb83-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">2014</span>, <span class="dv">2015</span>, <span class="dv">2016</span>, <span class="dv">2017</span>, <span class="dv">2018</span>, <span class="dv">2019</span>, <span class="dv">2022</span>, <span class="dv">2023</span>)) <span class="sc">+</span></span>
<span id="cb83-19"><a href="modeling-practice-and-qualifying-times.html#cb83-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lower_PI, <span class="at">ymax =</span> upper_PI), <span class="at">fill =</span> <span class="st">&#39;grey&#39;</span>, <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb83-20"><a href="modeling-practice-and-qualifying-times.html#cb83-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> .lower, <span class="at">ymax =</span> .upper), <span class="at">fill =</span> <span class="st">&#39;grey&#39;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb83-21"><a href="modeling-practice-and-qualifying-times.html#cb83-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb83-22"><a href="modeling-practice-and-qualifying-times.html#cb83-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-72-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br>
<br></p>
<div class="blackbox">
<div class="center">
<p><strong>Creating a prediction interval using the <code>augment()</code> function</strong></p>
</div>
<p>It’s just as easy to create a 95% prediction interval using augment.</p>
<p>In the example above, I use the following code to attach the 95% prediction interval to the Australia qualifying dataset:</p>
<p><code>augment(aus.lm, data = aus_quali_times, interval = "prediction", se_fit = T) %&gt;% rename("lower_PI" = ".lower", "upper_PI" = ".upper")</code></p>
<p>To avoid confusion, I renamed the lower and upper bounds of this prediction interval <code>lower_PI</code> and <code>upper_PI</code> respectively.</p>
<p>For more information on using <code>augment()</code>, visit this link: <a href="https://broom.tidymodels.org/reference/augment.lm.html" class="uri">https://broom.tidymodels.org/reference/augment.lm.html</a></p>
</div>
<p><br>
<br></p>
<p>As another reminder:</p>
<p><strong>The confidence interval is uncertainty surrounding a mean response, and the prediction interval is uncertainty surrounding a prediction of a future observation.</strong></p>
<p>Or, in our racing example above:</p>
<p>A confidence interval around the fit describes the uncertainty in predicting an <em>average</em> time for a given year, while the prediction interval describes the uncertainty in predicting any <em>single</em> time for a particular year.</p>
<p>In the next section, I will build on these ideas and add complexity to this simple linear regression model.</p>
</div>
</div>
<div id="interaction-model" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Interaction Model<a href="modeling-practice-and-qualifying-times.html#interaction-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>I would like to now expand my question a bit.</p>
<p><strong><em>How does qualifying time progression compare between the Australian Grand Prix and another race?</em></strong></p>
<p>To begin answering this question, I can take a similar modeling approach that I used for Australia, but apply it to another race. Let’s take a look at the Monaco Grand Prix. I’ll run through the same modeling steps below.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="modeling-practice-and-qualifying-times.html#cb84-1" aria-hidden="true" tabindex="-1"></a>practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb84-2"><a href="modeling-practice-and-qualifying-times.html#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Race <span class="sc">==</span> <span class="st">&#39;monaco&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb84-3"><a href="modeling-practice-and-qualifying-times.html#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Year, Q_secs)) <span class="sc">+</span></span>
<span id="cb84-4"><a href="modeling-practice-and-qualifying-times.html#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">w =</span> <span class="fl">0.3</span>), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb84-5"><a href="modeling-practice-and-qualifying-times.html#cb84-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb84-6"><a href="modeling-practice-and-qualifying-times.html#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Year&#39;</span>,</span>
<span id="cb84-7"><a href="modeling-practice-and-qualifying-times.html#cb84-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Best Qualifying Time (secs)&#39;</span>,</span>
<span id="cb84-8"><a href="modeling-practice-and-qualifying-times.html#cb84-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&#39;Monaco Grand Prix Qualifying&#39;</span>,</span>
<span id="cb84-9"><a href="modeling-practice-and-qualifying-times.html#cb84-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&#39;2014 - 2023&#39;</span>) <span class="sc">+</span></span>
<span id="cb84-10"><a href="modeling-practice-and-qualifying-times.html#cb84-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">2014</span>, <span class="dv">2015</span>, <span class="dv">2016</span>, <span class="dv">2017</span>, <span class="dv">2018</span>, <span class="dv">2019</span>, <span class="dv">2020</span>, <span class="dv">2021</span>, <span class="dv">2022</span>, <span class="dv">2023</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-73-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Interesting! We did not have data for Australia in 2020 and 2021 (due to the pandemic). In 2022, the new ground-effects regulations were introduced. Because we were missing data for Australia in 2020 and 2021, our model assumed a constant decrease in qualifying times.</p>
<p>Compare this result to Monaco, where we did have data for 2021. Progression does appear to steadily decrease through 2021, but times then increase in 2022 as the new regulations are introduced.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="modeling-practice-and-qualifying-times.html#cb85-1" aria-hidden="true" tabindex="-1"></a>practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb85-2"><a href="modeling-practice-and-qualifying-times.html#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Race <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;australia&#39;</span>, <span class="st">&#39;monaco&#39;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb85-3"><a href="modeling-practice-and-qualifying-times.html#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Year, Q_secs, <span class="at">col =</span> Race)) <span class="sc">+</span></span>
<span id="cb85-4"><a href="modeling-practice-and-qualifying-times.html#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">w =</span> <span class="fl">0.3</span>), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb85-5"><a href="modeling-practice-and-qualifying-times.html#cb85-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb85-6"><a href="modeling-practice-and-qualifying-times.html#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Year&#39;</span>,</span>
<span id="cb85-7"><a href="modeling-practice-and-qualifying-times.html#cb85-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Best Qualifying Time (secs)&#39;</span>,</span>
<span id="cb85-8"><a href="modeling-practice-and-qualifying-times.html#cb85-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="fu">title_color_coder</span>(<span class="st">&quot;&quot;</span>, <span class="st">&quot;Australia&quot;</span>, <span class="st">&#39;#F8766D&#39;</span>, <span class="st">&quot; vs &quot;</span>, <span class="st">&quot;Monaco&quot;</span>, <span class="st">&#39;#00BFC4&#39;</span> ,<span class="st">&quot; Qualifying Time Progression&quot;</span>), </span>
<span id="cb85-9"><a href="modeling-practice-and-qualifying-times.html#cb85-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&#39;2014 - 2023&#39;</span>,</span>
<span id="cb85-10"><a href="modeling-practice-and-qualifying-times.html#cb85-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&#39;&#39;</span>) <span class="sc">+</span> <span class="co"># use the title_color_coder() function</span></span>
<span id="cb85-11"><a href="modeling-practice-and-qualifying-times.html#cb85-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Race, <span class="at">scales=</span> <span class="st">&#39;free_y&#39;</span>) <span class="sc">+</span></span>
<span id="cb85-12"><a href="modeling-practice-and-qualifying-times.html#cb85-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">2014</span>, <span class="dv">2015</span>, <span class="dv">2016</span>, <span class="dv">2017</span>, <span class="dv">2018</span>, <span class="dv">2019</span>, <span class="dv">2020</span>, <span class="dv">2021</span>, <span class="dv">2022</span>, <span class="dv">2023</span>)) <span class="sc">+</span> </span>
<span id="cb85-13"><a href="modeling-practice-and-qualifying-times.html#cb85-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb85-14"><a href="modeling-practice-and-qualifying-times.html#cb85-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb85-15"><a href="modeling-practice-and-qualifying-times.html#cb85-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb85-16"><a href="modeling-practice-and-qualifying-times.html#cb85-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">strip.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb85-17"><a href="modeling-practice-and-qualifying-times.html#cb85-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>, <span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb85-18"><a href="modeling-practice-and-qualifying-times.html#cb85-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>),</span>
<span id="cb85-19"><a href="modeling-practice-and-qualifying-times.html#cb85-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>),</span>
<span id="cb85-20"><a href="modeling-practice-and-qualifying-times.html#cb85-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">15</span>),</span>
<span id="cb85-21"><a href="modeling-practice-and-qualifying-times.html#cb85-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb85-22"><a href="modeling-practice-and-qualifying-times.html#cb85-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> ggtext<span class="sc">::</span><span class="fu">element_markdown</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">20</span>)) <span class="do">## render the provided text as markdown/html</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-74-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>To quantitatively compare these two progression trends, we can build linear models for each race and compare the output. We should probably remove 2014 data (because Australia times were compromised by the rain), and 2021 data (because the Australian Grand Prix wasn’t held). And, it is probably wise to limit the data to one set of regulations (pre-2022). Below, I’ll re-plot the scatterplot with best-fit linear model lines for each race under these updated conditions.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="modeling-practice-and-qualifying-times.html#cb86-1" aria-hidden="true" tabindex="-1"></a>practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb86-2"><a href="modeling-practice-and-qualifying-times.html#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Race <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;australia&#39;</span>, <span class="st">&#39;monaco&#39;</span>),</span>
<span id="cb86-3"><a href="modeling-practice-and-qualifying-times.html#cb86-3" aria-hidden="true" tabindex="-1"></a>         Year <span class="sc">&gt;</span> <span class="dv">2014</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;</span> <span class="dv">2020</span>) <span class="sc">%&gt;%</span></span>
<span id="cb86-4"><a href="modeling-practice-and-qualifying-times.html#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Year, Q_secs, <span class="at">col =</span> Race)) <span class="sc">+</span></span>
<span id="cb86-5"><a href="modeling-practice-and-qualifying-times.html#cb86-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">w =</span> <span class="fl">0.3</span>), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb86-6"><a href="modeling-practice-and-qualifying-times.html#cb86-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="at">se =</span> F, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb86-7"><a href="modeling-practice-and-qualifying-times.html#cb86-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb86-8"><a href="modeling-practice-and-qualifying-times.html#cb86-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Year&#39;</span>,</span>
<span id="cb86-9"><a href="modeling-practice-and-qualifying-times.html#cb86-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Best Qualifying Time (secs)&#39;</span>,</span>
<span id="cb86-10"><a href="modeling-practice-and-qualifying-times.html#cb86-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="fu">title_color_coder</span>(<span class="st">&quot;&quot;</span>, <span class="st">&quot;Australia&quot;</span>, <span class="st">&#39;#F8766D&#39;</span>, <span class="st">&quot; vs &quot;</span>, <span class="st">&quot;Monaco&quot;</span>, <span class="st">&#39;#00BFC4&#39;</span> ,<span class="st">&quot; Qualifying Time Progression&quot;</span>), </span>
<span id="cb86-11"><a href="modeling-practice-and-qualifying-times.html#cb86-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&#39;2015 - 2019&#39;</span>,</span>
<span id="cb86-12"><a href="modeling-practice-and-qualifying-times.html#cb86-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&#39;&#39;</span>) <span class="sc">+</span> <span class="co"># use the title_color_coder() function</span></span>
<span id="cb86-13"><a href="modeling-practice-and-qualifying-times.html#cb86-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Race, <span class="at">scales=</span> <span class="st">&#39;free_y&#39;</span>) <span class="sc">+</span></span>
<span id="cb86-14"><a href="modeling-practice-and-qualifying-times.html#cb86-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">2014</span>, <span class="dv">2015</span>, <span class="dv">2016</span>, <span class="dv">2017</span>, <span class="dv">2018</span>, <span class="dv">2019</span>)) <span class="sc">+</span> </span>
<span id="cb86-15"><a href="modeling-practice-and-qualifying-times.html#cb86-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb86-16"><a href="modeling-practice-and-qualifying-times.html#cb86-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb86-17"><a href="modeling-practice-and-qualifying-times.html#cb86-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)  <span class="sc">+</span></span>
<span id="cb86-18"><a href="modeling-practice-and-qualifying-times.html#cb86-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">strip.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb86-19"><a href="modeling-practice-and-qualifying-times.html#cb86-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>, <span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb86-20"><a href="modeling-practice-and-qualifying-times.html#cb86-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>),</span>
<span id="cb86-21"><a href="modeling-practice-and-qualifying-times.html#cb86-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>),</span>
<span id="cb86-22"><a href="modeling-practice-and-qualifying-times.html#cb86-22" aria-hidden="true" tabindex="-1"></a>         <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">15</span>),</span>
<span id="cb86-23"><a href="modeling-practice-and-qualifying-times.html#cb86-23" aria-hidden="true" tabindex="-1"></a>         <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb86-24"><a href="modeling-practice-and-qualifying-times.html#cb86-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> ggtext<span class="sc">::</span><span class="fu">element_markdown</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">20</span>)) <span class="do">## render the provided text as markdown/html</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-75-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>With the naked eye, it looks like Australia’s slope is steeper, suggesting that times improved at a quicker rate relative to Monaco. But, we should calculate the slope estimates and the 95% confidence intervals around the slope estimate to quantitatively compare.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="modeling-practice-and-qualifying-times.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filter times to include only clean Australian data</span></span>
<span id="cb87-2"><a href="modeling-practice-and-qualifying-times.html#cb87-2" aria-hidden="true" tabindex="-1"></a>aus_quali_times <span class="ot">&lt;-</span> practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb87-3"><a href="modeling-practice-and-qualifying-times.html#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Race <span class="sc">==</span> <span class="st">&#39;australia&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb87-4"><a href="modeling-practice-and-qualifying-times.html#cb87-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Q_secs),</span>
<span id="cb87-5"><a href="modeling-practice-and-qualifying-times.html#cb87-5" aria-hidden="true" tabindex="-1"></a>         Year <span class="sc">&gt;</span> <span class="dv">2014</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;</span> <span class="dv">2020</span>)</span>
<span id="cb87-6"><a href="modeling-practice-and-qualifying-times.html#cb87-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-7"><a href="modeling-practice-and-qualifying-times.html#cb87-7" aria-hidden="true" tabindex="-1"></a><span class="co"># fit linear model for Australia</span></span>
<span id="cb87-8"><a href="modeling-practice-and-qualifying-times.html#cb87-8" aria-hidden="true" tabindex="-1"></a>aus.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Q_secs <span class="sc">~</span> Year, aus_quali_times)</span>
<span id="cb87-9"><a href="modeling-practice-and-qualifying-times.html#cb87-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-10"><a href="modeling-practice-and-qualifying-times.html#cb87-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% CI slope</span></span>
<span id="cb87-11"><a href="modeling-practice-and-qualifying-times.html#cb87-11" aria-hidden="true" tabindex="-1"></a>aus_coef_ci <span class="ot">&lt;-</span> <span class="fu">confint</span>(aus.lm)</span>
<span id="cb87-12"><a href="modeling-practice-and-qualifying-times.html#cb87-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-13"><a href="modeling-practice-and-qualifying-times.html#cb87-13" aria-hidden="true" tabindex="-1"></a><span class="co"># filter times to include only clean Australian data</span></span>
<span id="cb87-14"><a href="modeling-practice-and-qualifying-times.html#cb87-14" aria-hidden="true" tabindex="-1"></a>mon_quali_times <span class="ot">&lt;-</span> practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb87-15"><a href="modeling-practice-and-qualifying-times.html#cb87-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Race <span class="sc">==</span> <span class="st">&#39;monaco&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb87-16"><a href="modeling-practice-and-qualifying-times.html#cb87-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Q_secs),</span>
<span id="cb87-17"><a href="modeling-practice-and-qualifying-times.html#cb87-17" aria-hidden="true" tabindex="-1"></a>         Year <span class="sc">&gt;</span> <span class="dv">2014</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;</span> <span class="dv">2020</span>)</span>
<span id="cb87-18"><a href="modeling-practice-and-qualifying-times.html#cb87-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-19"><a href="modeling-practice-and-qualifying-times.html#cb87-19" aria-hidden="true" tabindex="-1"></a><span class="co"># fit linear model for Monaco</span></span>
<span id="cb87-20"><a href="modeling-practice-and-qualifying-times.html#cb87-20" aria-hidden="true" tabindex="-1"></a>mon.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Q_secs <span class="sc">~</span> Year, <span class="at">data =</span> mon_quali_times)</span>
<span id="cb87-21"><a href="modeling-practice-and-qualifying-times.html#cb87-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-22"><a href="modeling-practice-and-qualifying-times.html#cb87-22" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% CI slope</span></span>
<span id="cb87-23"><a href="modeling-practice-and-qualifying-times.html#cb87-23" aria-hidden="true" tabindex="-1"></a>mon_coef_ci <span class="ot">&lt;-</span> <span class="fu">confint</span>(mon.lm)</span></code></pre></div>
<p>I will plot the slopes ± 95% confidence intervals here:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="modeling-practice-and-qualifying-times.html#cb88-1" aria-hidden="true" tabindex="-1"></a>aus_v_mon <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">data.frame</span>(<span class="at">australia =</span> <span class="fu">cbind</span>(<span class="at">est =</span> <span class="fu">coef</span>(aus.lm), aus_coef_ci)[<span class="dv">2</span>,]), </span>
<span id="cb88-2"><a href="modeling-practice-and-qualifying-times.html#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">monaco =</span> <span class="fu">cbind</span>(<span class="at">est =</span> <span class="fu">coef</span>(mon.lm), mon_coef_ci)[<span class="dv">2</span>,])) <span class="sc">%&gt;%</span> <span class="fu">t</span>() <span class="sc">%&gt;%</span></span>
<span id="cb88-3"><a href="modeling-practice-and-qualifying-times.html#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb88-4"><a href="modeling-practice-and-qualifying-times.html#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="at">var =</span> <span class="st">&#39;race&#39;</span>)</span>
<span id="cb88-5"><a href="modeling-practice-and-qualifying-times.html#cb88-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-6"><a href="modeling-practice-and-qualifying-times.html#cb88-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-7"><a href="modeling-practice-and-qualifying-times.html#cb88-7" aria-hidden="true" tabindex="-1"></a>aus_v_mon <span class="sc">%&gt;%</span></span>
<span id="cb88-8"><a href="modeling-practice-and-qualifying-times.html#cb88-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb88-9"><a href="modeling-practice-and-qualifying-times.html#cb88-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> est, <span class="at">ymin =</span> <span class="st">`</span><span class="at">2.5 %</span><span class="st">`</span>, <span class="at">ymax =</span> <span class="st">`</span><span class="at">97.5 %</span><span class="st">`</span>, <span class="at">col =</span> race), </span>
<span id="cb88-10"><a href="modeling-practice-and-qualifying-times.html#cb88-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">linewidth =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb88-11"><a href="modeling-practice-and-qualifying-times.html#cb88-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb88-12"><a href="modeling-practice-and-qualifying-times.html#cb88-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="st">&#39;&#39;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;australia&quot;</span> <span class="ot">=</span> <span class="st">&#39;#F8766D&#39;</span>, <span class="st">&quot;monaco&quot;</span> <span class="ot">=</span> <span class="st">&#39;#00BFC4&#39;</span>)) <span class="sc">+</span> </span>
<span id="cb88-13"><a href="modeling-practice-and-qualifying-times.html#cb88-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Grand Prix&#39;</span>, <span class="at">y =</span> <span class="st">&#39;Coefficient Estimate \u00b1 95% CI&#39;</span>,</span>
<span id="cb88-14"><a href="modeling-practice-and-qualifying-times.html#cb88-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="fu">title_color_coder</span>(<span class="st">&quot;&quot;</span>, <span class="st">&quot;Australia&quot;</span>, <span class="st">&#39;#F8766D&#39;</span>, <span class="st">&quot; vs &quot;</span>, <span class="st">&quot;Monaco&quot;</span>, <span class="st">&#39;#00BFC4&#39;</span> ,<span class="st">&quot; Qualifying Time Progression&quot;</span>), </span>
<span id="cb88-15"><a href="modeling-practice-and-qualifying-times.html#cb88-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&#39;2015 - 2019&#39;</span>) <span class="sc">+</span> </span>
<span id="cb88-16"><a href="modeling-practice-and-qualifying-times.html#cb88-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb88-17"><a href="modeling-practice-and-qualifying-times.html#cb88-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb88-18"><a href="modeling-practice-and-qualifying-times.html#cb88-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-19"><a href="modeling-practice-and-qualifying-times.html#cb88-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> ggtext<span class="sc">::</span><span class="fu">element_markdown</span>()) <span class="do">## render the provided text as markdown/html</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-77-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>So, while my initial guess that qualifying times decreased at a more rapid rate in Australia, the 95% confidence intervals for the slope estimates largely overlap. This suggests that there’s little to no statistical evidence that these slopes are in fact different.</p>
<p>But, a more proper way to make this comparison is by using an <strong>interaction model</strong>. It can answer the question that we had (i.e. <em>Was qualifying time progression different between the two races?</em>), and it can do a lot more. Below, I’ll fit an interaction model to the 2015 - 2019 data for the Australian and Monaco Grands Prix.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="modeling-practice-and-qualifying-times.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filter data</span></span>
<span id="cb89-2"><a href="modeling-practice-and-qualifying-times.html#cb89-2" aria-hidden="true" tabindex="-1"></a>aus_mon_data <span class="ot">&lt;-</span> practice_and_qualifying <span class="sc">%&gt;%</span></span>
<span id="cb89-3"><a href="modeling-practice-and-qualifying-times.html#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Race <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;australia&#39;</span>, <span class="st">&#39;monaco&#39;</span>),</span>
<span id="cb89-4"><a href="modeling-practice-and-qualifying-times.html#cb89-4" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(Q_secs),</span>
<span id="cb89-5"><a href="modeling-practice-and-qualifying-times.html#cb89-5" aria-hidden="true" tabindex="-1"></a>         Year <span class="sc">&gt;</span> <span class="dv">2014</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;</span> <span class="dv">2020</span>) <span class="sc">%&gt;%</span></span>
<span id="cb89-6"><a href="modeling-practice-and-qualifying-times.html#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Race =</span> <span class="fu">factor</span>(Race))</span>
<span id="cb89-7"><a href="modeling-practice-and-qualifying-times.html#cb89-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-8"><a href="modeling-practice-and-qualifying-times.html#cb89-8" aria-hidden="true" tabindex="-1"></a><span class="co"># fit an interaction model</span></span>
<span id="cb89-9"><a href="modeling-practice-and-qualifying-times.html#cb89-9" aria-hidden="true" tabindex="-1"></a>aus.mon.int.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Q_secs <span class="sc">~</span> Year<span class="sc">:</span>Race, <span class="at">data =</span> aus_mon_data)</span>
<span id="cb89-10"><a href="modeling-practice-and-qualifying-times.html#cb89-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-11"><a href="modeling-practice-and-qualifying-times.html#cb89-11" aria-hidden="true" tabindex="-1"></a><span class="co"># print the model output</span></span>
<span id="cb89-12"><a href="modeling-practice-and-qualifying-times.html#cb89-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aus.mon.int.lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Q_secs ~ Year:Race, data = aus_mon_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.0609 -0.9699 -0.1678  0.7731  9.2456 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        3236.76129  166.49551   19.44   &lt;2e-16 ***
## Year:Raceaustralia   -1.56248    0.08255  -18.93   &lt;2e-16 ***
## Year:Racemonaco      -1.56793    0.08255  -18.99   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.638 on 197 degrees of freedom
## Multiple R-squared:  0.9292, Adjusted R-squared:  0.9285 
## F-statistic:  1294 on 2 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>At first, the output may seem a bit confusing, but it only requires a small adjustment. This model produces coefficient estimates for a race-specific intercept and slope, relative to the ‘base-level’. In this case, Australia is the base level. Luckily, we can actually use functions from the <strong>emmeans</strong> package to easily estimate the coefficient and confidence intervals by race. <strong>emmeans</strong> stands for <em>estimated marginal means</em>, which are means for treatment levels that are adjusted for means of other factors in the model. In this example, we are interested in the influence of year on qualifying times, which is also impacted by the circuit. I will use the handy <code>emtrends()</code> function to tidy up this model’s results.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="modeling-practice-and-qualifying-times.html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emtrends</span>(aus.mon.int.lm, pairwise <span class="sc">~</span> Race, <span class="at">var =</span> <span class="st">&#39;Year&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb91-2"><a href="modeling-practice-and-qualifying-times.html#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb91-3"><a href="modeling-practice-and-qualifying-times.html#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Race <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;australia&#39;</span>, <span class="st">&#39;monaco&#39;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb91-4"><a href="modeling-practice-and-qualifying-times.html#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb91-5"><a href="modeling-practice-and-qualifying-times.html#cb91-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">x =</span> Race, <span class="at">y =</span> Year.trend, <span class="at">ymin =</span> lower.CL, <span class="at">ymax =</span> upper.CL, <span class="at">col =</span> Race), </span>
<span id="cb91-6"><a href="modeling-practice-and-qualifying-times.html#cb91-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">linewidth =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb91-7"><a href="modeling-practice-and-qualifying-times.html#cb91-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb91-8"><a href="modeling-practice-and-qualifying-times.html#cb91-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="st">&#39;&#39;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;australia&quot;</span> <span class="ot">=</span> <span class="st">&#39;#F8766D&#39;</span>, <span class="st">&quot;monaco&quot;</span> <span class="ot">=</span> <span class="st">&#39;#00BFC4&#39;</span>)) <span class="sc">+</span> </span>
<span id="cb91-9"><a href="modeling-practice-and-qualifying-times.html#cb91-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Grand Prix&#39;</span>, <span class="at">y =</span> <span class="st">&#39;Coefficient Estimate \u00b1 95% CI&#39;</span>,</span>
<span id="cb91-10"><a href="modeling-practice-and-qualifying-times.html#cb91-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="fu">title_color_coder</span>(<span class="st">&quot;&quot;</span>, <span class="st">&quot;Australia&quot;</span>, <span class="st">&#39;#F8766D&#39;</span>, <span class="st">&quot; vs &quot;</span>, <span class="st">&quot;Monaco&quot;</span>, <span class="st">&#39;#00BFC4&#39;</span> ,<span class="st">&quot; Qualifying Time Progression&quot;</span>), </span>
<span id="cb91-11"><a href="modeling-practice-and-qualifying-times.html#cb91-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&#39;Interaction Model: 2015 - 2019&#39;</span>) <span class="sc">+</span> </span>
<span id="cb91-12"><a href="modeling-practice-and-qualifying-times.html#cb91-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb91-13"><a href="modeling-practice-and-qualifying-times.html#cb91-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>( <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb91-14"><a href="modeling-practice-and-qualifying-times.html#cb91-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> ggtext<span class="sc">::</span><span class="fu">element_markdown</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="do">## render the provided text as markdown/html</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-79-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br>
<br></p>
<div class="blackbox">
<div class="center">
<p><strong>the emmeans package</strong></p>
</div>
<p>Estimated marginal means (EMMs), a.k.a. least-squares means, are predictions on a reference grid of predictor settings, or marginal averages.</p>
<p>To estimate the marginal means of a model, simply run <code>emmeans(model, pairwise ~ treatment)</code>. However, more thought should go into the use of this function. This is particularly true for more complicated models.</p>
<p>The <code>emtrends()</code> function is useful when a fitted model involves a numerical predictor x interacting with another predictor a (typically a factor). This si the case with our interaction model where we have <code>year</code> (numeric) interacting with <code>race</code> (factor).</p>
<p>For more information on using the <strong>emmeans</strong> package, visit these links: <a href="https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html" class="uri">https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html</a></p>
<p><a href="https://rdrr.io/cran/emmeans/f/vignettes/FAQs.Rmd" class="uri">https://rdrr.io/cran/emmeans/f/vignettes/FAQs.Rmd</a></p>
<p><a href="https://rdrr.io/cran/emmeans/man/emtrends.html" class="uri">https://rdrr.io/cran/emmeans/man/emtrends.html</a></p>
</div>
<p><br>
<br></p>
<p>While the estimates for the slope remain the same to those estimated with individual models, the 95% confidence intervals are narrower for this interaction model. Nonetheless, it doesn’t change our opinion that the rate of qualifying time improvement is not statistically different between these two races during this time period (2015 - 2019).</p>
<p>As we did for a single race earlier, we can use the <code>augment()</code> function to estimate the 95% confidence and 95% prediction intervals for this interaction model.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="modeling-practice-and-qualifying-times.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the 95% confidence interval for the fit line</span></span>
<span id="cb92-2"><a href="modeling-practice-and-qualifying-times.html#cb92-2" aria-hidden="true" tabindex="-1"></a>aus_v_mon_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(aus.mon.int.lm, <span class="at">data =</span> aus_mon_data, <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>, <span class="at">se_fit =</span> T)</span>
<span id="cb92-3"><a href="modeling-practice-and-qualifying-times.html#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="modeling-practice-and-qualifying-times.html#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the 95% prediction interval for the fit line</span></span>
<span id="cb92-5"><a href="modeling-practice-and-qualifying-times.html#cb92-5" aria-hidden="true" tabindex="-1"></a>aus_mon_aug_pr <span class="ot">&lt;-</span> <span class="fu">augment</span>(aus.mon.int.lm, <span class="at">data =</span> aus_mon_data, <span class="at">interval =</span> <span class="st">&quot;prediction&quot;</span>, <span class="at">se_fit =</span> T) <span class="sc">%&gt;%</span></span>
<span id="cb92-6"><a href="modeling-practice-and-qualifying-times.html#cb92-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rename</span>(<span class="st">&quot;lower_PI&quot;</span> <span class="ot">=</span> <span class="st">&quot;.lower&quot;</span>, <span class="st">&quot;upper_PI&quot;</span> <span class="ot">=</span> <span class="st">&quot;.upper&quot;</span>)</span>
<span id="cb92-7"><a href="modeling-practice-and-qualifying-times.html#cb92-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-8"><a href="modeling-practice-and-qualifying-times.html#cb92-8" aria-hidden="true" tabindex="-1"></a><span class="co"># combine the intervals</span></span>
<span id="cb92-9"><a href="modeling-practice-and-qualifying-times.html#cb92-9" aria-hidden="true" tabindex="-1"></a>aus_v_mon_aug <span class="ot">&lt;-</span> aus_v_mon_aug <span class="sc">%&gt;%</span></span>
<span id="cb92-10"><a href="modeling-practice-and-qualifying-times.html#cb92-10" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_cols</span>(aus_mon_aug_pr <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(lower_PI, upper_PI))</span>
<span id="cb92-11"><a href="modeling-practice-and-qualifying-times.html#cb92-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-12"><a href="modeling-practice-and-qualifying-times.html#cb92-12" aria-hidden="true" tabindex="-1"></a>aus_v_mon_aug <span class="sc">%&gt;%</span> </span>
<span id="cb92-13"><a href="modeling-practice-and-qualifying-times.html#cb92-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Year, Q_secs, <span class="at">col =</span> Race), <span class="at">show.legend =</span> F) <span class="sc">+</span></span>
<span id="cb92-14"><a href="modeling-practice-and-qualifying-times.html#cb92-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">seed=</span> <span class="dv">123</span>, <span class="at">h =</span> <span class="dv">0</span>, <span class="at">w =</span> <span class="fl">0.3</span>), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb92-15"><a href="modeling-practice-and-qualifying-times.html#cb92-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="at">se =</span> F, <span class="at">size =</span> <span class="fl">0.3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb92-16"><a href="modeling-practice-and-qualifying-times.html#cb92-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb92-17"><a href="modeling-practice-and-qualifying-times.html#cb92-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Year&#39;</span>,</span>
<span id="cb92-18"><a href="modeling-practice-and-qualifying-times.html#cb92-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Best Qualifying Time (secs)&#39;</span>,</span>
<span id="cb92-19"><a href="modeling-practice-and-qualifying-times.html#cb92-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="fu">title_color_coder</span>(<span class="st">&quot;&quot;</span>, <span class="st">&quot;Australia&quot;</span>, <span class="st">&#39;#F8766D&#39;</span>, <span class="st">&quot; vs &quot;</span>, <span class="st">&quot;Monaco&quot;</span>, <span class="st">&#39;#00BFC4&#39;</span> ,<span class="st">&quot; Qualifying Time Progression&quot;</span>),</span>
<span id="cb92-20"><a href="modeling-practice-and-qualifying-times.html#cb92-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&#39;Linear Model, 95% CI, and 95% PI (2015 - 2019)&#39;</span>) <span class="sc">+</span></span>
<span id="cb92-21"><a href="modeling-practice-and-qualifying-times.html#cb92-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">2014</span>, <span class="dv">2015</span>, <span class="dv">2016</span>, <span class="dv">2017</span>, <span class="dv">2018</span>, <span class="dv">2019</span>, <span class="dv">2020</span>, <span class="dv">2021</span>, <span class="dv">2022</span>, <span class="dv">2023</span>)) <span class="sc">+</span></span>
<span id="cb92-22"><a href="modeling-practice-and-qualifying-times.html#cb92-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lower_PI, <span class="at">ymax =</span> upper_PI), <span class="at">fill =</span> <span class="st">&#39;grey&#39;</span>, <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb92-23"><a href="modeling-practice-and-qualifying-times.html#cb92-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> .lower, <span class="at">ymax =</span> .upper), <span class="at">fill =</span> <span class="st">&#39;grey&#39;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb92-24"><a href="modeling-practice-and-qualifying-times.html#cb92-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb92-25"><a href="modeling-practice-and-qualifying-times.html#cb92-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">strip.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb92-26"><a href="modeling-practice-and-qualifying-times.html#cb92-26" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>, <span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb92-27"><a href="modeling-practice-and-qualifying-times.html#cb92-27" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>),</span>
<span id="cb92-28"><a href="modeling-practice-and-qualifying-times.html#cb92-28" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>),</span>
<span id="cb92-29"><a href="modeling-practice-and-qualifying-times.html#cb92-29" aria-hidden="true" tabindex="-1"></a>         <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">15</span>),</span>
<span id="cb92-30"><a href="modeling-practice-and-qualifying-times.html#cb92-30" aria-hidden="true" tabindex="-1"></a>         <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb92-31"><a href="modeling-practice-and-qualifying-times.html#cb92-31" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> ggtext<span class="sc">::</span><span class="fu">element_markdown</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">20</span>)) <span class="sc">+</span> <span class="do">## render the provided text as markdown/html</span></span>
<span id="cb92-32"><a href="modeling-practice-and-qualifying-times.html#cb92-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Race)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-80-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>This visual helps highlight that these slopes are not statistically different from each other.</p>
<p>As a reminder, each Grand Prix’s line describes the linear regression model’s estimate of average qualifying time for each year of the race. The inner band represents the 95% confidence interval of the prediction (confidence in the average response), and the outer band represents the 95% prediction interval of the prediction (confidence in a single response).</p>
<p>And for yet another reminder….</p>
<p><strong>The confidence interval is uncertainty surrounding a <em>mean response</em>, and the prediction interval is uncertainty surrounding a prediction of a <em>future observation</em>.</strong></p>
<p>The confidence interval width is driven by our uncertainty in the coefficient estimates. The prediction interval width is driven by both the uncertainty in the coefficient estimates and <em>unmodeled</em> variance. So, even if we had a very large sample size and were very confident in our coefficient estimates, our predicted values would still vary by the residual standard error of the model (i.e. the RSE in the <code>summary()</code> output).</p>
<p><br>
<br></p>
<div class="blackbox">
<div class="center">
<p><strong>Residual Standard Error (RSE)</strong></p>
</div>
<p>The Residual Standard Error (RSE) is the standard deviation of the residuals for a model. It is commonly used as a measure of how well a regression model fits a dataset.</p>
<p>In the interaction model above, the RSE is 1.587, meaning that the actual qualifying time with deviate from the true regression line by about 1.587 seconds, on average.</p>
<p>So, a lose interpretation of RSE is:</p>
<p><em>RSE, is the average amount that the response will deviate from the true regression line.</em></p>
</div>
<p><br>
<br></p>
</div>
<div id="next-chapter-2" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Next Chapter<a href="modeling-practice-and-qualifying-times.html#next-chapter-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the next chapter, we will look at driver performance.</p>
<div style="page-break-after: always;"></div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="qualifying.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="drivers.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/03-practice_v_qualifying.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
